### ISSUE TITLE
Question about the dataset format

### ISSUE THREAD

**Issue by yisuanwang** [wqyin/WHAC#6]
Great work! Could you provide any code to help parse the dataset format? (synbody_whac_DuetDance-20240218_240426_200_test_camera-000_0.01.npz)
I see that the motion sequence given includes the following:
```
betas: (105884, 10)
transl: (105884, 3)
global_orient: (105884, 3)
body_pose: (105884, 21, 3)
left_hand_pose: (105884, 15, 3)
right_hand_pose: (105884, 15, 3)
leye_pose: (105884, 3)
reye_pose: (105884, 3)
jaw_pose: (105884, 3)
expression: (105884, 10)
```
Could you share the code to parse this kind of format?

**Comment by johndpope** [comment]
these resources may help
https://synbody.github.io/
https://github.com/menyifang/En3D

**Comment by yisuanwang** [comment]
> these resources may help https://synbody.github.io/ https://github.com/menyifang/En3D

thanks, this is useful for me!
